### ISSUE TITLE
Release-version quits unexpectedly without feedback

### ISSUE THREAD

**Issue by ecamellini** [FrancescoCioria/smooth-release#118]
On master, if I run `npm run release-version`, the command quits without any feedback after the first step, no matter if I enter `y` or `n` as answer:

![image](https://user-images.githubusercontent.com/6418684/65873156-9b2a3900-e382-11e9-94ca-17ab18199cef.png)

**Comment by ecamellini** [comment]
@giogonzo could you try and see if you can reproduce this? I'm not sure it because we merged #116 or if it was already happening on this project.

**Comment by giogonzo** [comment]
@ecamellini I can confirm the crash. I did a quick check and the step crashing seems to be `--npm-version` which is not crashing before the last merge of #116 (I had to disable `--validations` to be able to test it, so might be related to the two together)

**Comment by ecamellini** [comment]
Let's just revert, since this is not really needed right now and lodash can just be updated on projects that depend on `smooth-release` by removing it from the `yarn.lock`. #119 reverts this
