### ISSUE TITLE
Error messages not displayed properly on node 7

### ISSUE THREAD

**Issue by dhinus** [FrancescoCioria/smooth-release#64]
# description

When a validation fails, instead of seeing a nice error message, I see this:

```
 TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
    at Function.defineProperty (<anonymous>)
    at new ErrorEXError (/usr/local/lib/node_modules/smooth-release/node_modules/error-ex/index.js:79:10)
```

# how to reproduce

- use `node@7`
- generate an error condition, e.g. logout from npm or create an untracked file

**Comment by FrancescoCioria** [comment]
@dhinus I'm having trouble reproducing this.
I always see the error correctly:

![image](https://cloud.githubusercontent.com/assets/4029499/22303773/144d8c0c-e335-11e6-931a-b620eddef032.png)

can you tell me:
- which validation was failing?
- which version of node where you using?

**Comment by FrancescoCioria** [comment]
I found this: https://github.com/Qix-/node-error-ex/issues/6

It looks like it could be `error-ex`'s fault... we may consider reverting #59

UPDATE: yes, it's `error-x`'s fault, but it happens only on `node@7`

**Comment by dhinus** [comment]
I was indeed using `node@7`. We can wait a bit and see if Qix-/node-error-ex#6 gets fixed.

**Comment by sindresorhus** [comment]
> We can wait a bit and see if Qix-/node-error-ex#6 gets fixed.

It's fixed.

**Comment by FrancescoCioria** [comment]
Yes, tested and it works :)
Thank you!

PS: we don't need to change anything as `smooth-release` requires `error-ex@^1.3.0` which will automatically install the current `1.3.0` version
